const FirstFamData = [
  {
    index: 0,
    name: "Mr. Abhinam Dutta",
    dept: "CH",
    mail: "abhinamdutta.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753920/Abhinam_Dutta_rupd1f_uhbhxv.avif",
    linkedIn: "https://www.linkedin.com/in/duttaabhinam",
    hall: "JCB",
  },
  {
    index: 1,
    name: "Mr. Akhilesh Dixit",
    dept: "EE",
    mail: "akhileshdixit07.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753917/Akhil_Dixit_qlwruw_s0bq6w.avif",
    linkedIn: "",
    hall: "MMM",
  },
  {
    index: 2,
    name: "Mr. Akshat Sharma",
    dept: "MI",
    mail: "akshatsharma7922.iitkgp.kgpian.ac.in@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753921/akh_xf6njp.avif",
    linkedIn: "",
    hall: "Patel",
  },
  {
    index: 3,
    name: "Mr. Aman rathore",
    dept: "CH",
    mail: "rathoreaman786.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753919/Aman_Rathore_ovgi1f_ipuiis.avif",
    linkedIn: "https://www.linkedin.com/in/aman-rathore-65589831a",
    hall: "VS",
  },
  {
    index: 4,
    name: "Mr. Amit Kumar",
    dept: "ME",
    mail: "amitkumar2024jan.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753919/Amit_Kumar_djogic_uqvcll.avif",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 5,
    name: "Mr. Anuruddh kumar",
    dept: "AG",
    mail: "kumarpushpendra02817.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753921/Anuruddh_Yadav_gmv5bq_aebsm0.avif",
    linkedIn: "",
    hall: "RK",
  },
  {
    index: 6,
    name: "Mr. Aryan Dhangar",
    dept: "HS",
    mail: "aryandhangar000.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753920/Aryan_Dhangar_w35n18_hhlmlt.avif",
    linkedIn: "",
    hall: "HJB",
  },
  {
    index: 7,
    name: "Mr. Avinash Sappati",
    dept: "AI",
    mail: "Avinash03.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753925/Avinash_cns2hn_eyakm7.avif",
    linkedIn: "https://www.linkedin.com/in/avinash-sappati-9435b7313",
    hall: "MS",
  },
  {
    index: 8,
    name: "Mr. Ayan Mallick",
    dept: "IE",
    mail: "mallikayan54.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753923/Ayan_Mallick_ncv6ol_gmpg4s.avif",
    linkedIn: "https://www.linkedin.com/in/ayan-mallick-343865312",
    hall: "Azad",
  },
  {
    index: 9,
    name: "Mr. Ayush kumar",
    dept: "MI",
    mail: "ayushkumar.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753929/Ayush_Kumar_evlkss_yucqfr.avif",
    linkedIn: "",
    hall: "MS",
  },
  {
    index: 10,
    name: "Mr. Bibek Biswas",
    dept: "AE",
    mail: "biswasbibek438@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753924/Bibek_Biswas_qvz9uy_rkdxex.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 11,
    name: "Ms. Chetna kanesh",
    dept: "AE",
    mail: "kc277e.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753930/Chetna_Kanesh_kv7cuo_m3qbkq.avif",
    linkedIn: "",
    hall: "SN/IG",
  },
  {
    index: 12,
    name: "Mr. Deepesh",
    dept: "EC",
    mail: "deepeshashthana.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753927/Deepesh_Ashthana_e39vq0_p0gfmz.avif",
    linkedIn: "",
    hall: "MS",
  },
  {
    index: 13,
    name: "Mr. Dhananjay Sarkar",
    dept: "CH",
    mail: "Dhananjay Sarkar",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753926/Dhananjay_Sarkar_ccwrrj_x5iiog.avif",
    linkedIn: "https://www.linkedin.com/in/dhananjay-sarkar-55aa24319",
    hall: "MMM",
  },
  {
    index: 14,
    name: "Mr. Golu Kumar Sagar",
    dept: "CY",
    mail: "gksagar98765.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753927/Golu_Kumar_Sagar_oiwhim_bnqpfq.avif",
    linkedIn: "G.K.Sagar",
    hall: "RP",
  },
  {
    index: 15,
    name: "Mr. Himanshu Malik",
    dept: "CY",
    mail: "malikhimanshu.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753927/Himanshu_Malik_wmo5ud_u5yqrc.avif",
    linkedIn: "https://www.linkedin.com/in/himanshu-malik-a3aa0331a",
    hall: "Azad",
  },
  {
    index: 16,
    name: "Mr. Hiran Jyoti Deori",
    dept: "MT",
    mail: "hiron1234deori.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753928/Hiran_Deori_d8pl4m_ioytag.avif",
    linkedIn: "",
    hall: "LLR",
  },
  {
    index: 17,
    name: "Mr. Mayank Singh",
    dept: "CS",
    mail: "mayanksingh2007.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753945/Mayank_Singh_aaj0dg_m6ymbr.avif",
    linkedIn: "",
    hall: "Azad",
  },
  {
    index: 18,
    name: "Ms. Monika Dhakad",
    dept: "IE",
    mail: "monikadhakad135.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753952/Monika_Dhakad_nhzfmf_pybofo.avif",
    linkedIn: "",
    hall: "SN/IG",
  },
  {
    index: 19,
    name: "Ms. Muskan varma",
    dept: "AE",
    mail: "muskanvarma.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753945/Muskan_varma_hkvx52_y9qh6a.avif",
    linkedIn: "",
    hall: "SNVH",
  },
  {
    index: 20,
    name: "Mr. Nayan Balpande",
    dept: "IM",
    mail: "nayanbalpa.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753945/Nayan_Balpande_fagifz_kbshxp.avif",
    linkedIn: "https://www.linkedin.com/in/nayan-balpande-2ba1a0326",
    hall: "Azad",
  },
  {
    index: 21,
    name: "Mr. Nisit kumar",
    dept: "NA",
    mail: "nisitkumar.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753945/Nisit_Kumar_hcrotq_ssluhz.avif",
    linkedIn: "Nisit kumar",
    hall: "RP",
  },
  {
    index: 22,
    name: "Mr. Prabhat Prajapati",
    dept: "EE",
    mail: "prabhatprajapati9302.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753946/Prabhat_Prajapati_ysvqsj_nuqz0g.avif",
    linkedIn: "",
    hall: "MMM",
  },
  {
    index: 23,
    name: "Mr. Prabin Kumar Bhoi",
    dept: "NA",
    mail: "bhoiprabin23.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753951/Prabin_Kumar_Bhoi_g85btt_yyua8e.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 24,
    name: "Mr. Prashik Mane",
    dept: "BT",
    mail: "prashikmane1412.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753948/Prashik_Mane_ov7x4j_p3ruin.avif",
    linkedIn: "",
    hall: "MS",
  },
  {
    index: 25,
    name: "Mr. Pratik Verma",
    dept: "CS",
    mail: "pratikverma.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753949/Pratik_Verma_nirhu7_uorhgb.avif",
    linkedIn:
      "https://www.linkedin.com/in/verma-pratik?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    hall: "RK",
  },
  {
    index: 26,
    name: "Ms. Preeti Choudhary",
    dept: "EE",
    mail: "preeti.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753949/Preeti_Choudhary_padnkp_fruso1.avif",
    linkedIn: "",
    hall: "SN/IG",
  },
  {
    index: 27,
    name: "Mr. Priyanshu Gautam",
    dept: "CH",
    mail: "priyanshu234.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753952/Priyanshu_Gautam_vr6mku_hac98d.avif",
    linkedIn: "",
    hall: "Patel",
  },
  {
    index: 28,
    name: "Mr. Priyanshu Gupta",
    dept: "IE",
    mail: "priyanshu.g.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753963/Priyanshu_Gupta_f6h8tl_uxtfwv.avif",
    linkedIn:
      "https://www.linkedin.com/in/priyanshu-gupta-590b4931b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    hall: "MMM",
  },
  {
    index: 29,
    name: "Mr. Rahul Borkar",
    dept: "EE",
    mail: "rahul2309.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747750668/Rahul_Borkar_m15fy5.avif",
    linkedIn: "",
    hall: "RK",
  },
  {
    index: 30,
    name: "Mr. Rajesh Kumar Behera",
    dept: "MA",
    mail: "rajeshkumar.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747750668/Rajesh_Kumar_Bahera_pjeyzk.avif",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 31,
    name: "Mr. Rajmal Murmu",
    dept: "CE",
    mail: "rajmalmurmu1724.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747750668/Rajmal_Murmu_jyyj2t.avif",
    linkedIn: "",
    hall: "Patel",
  },
  {
    index: 32,
    name: "Mr. Rishikesh kumar",
    dept: "MI",
    mail: "rishikeshkumar53526.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753963/Rishikesh_zypbdd_mgrace.avif",
    linkedIn: "",
    hall: "MMM",
  },
  {
    index: 33,
    name: "Mr. Sachin Kumar",
    dept: "CS",
    mail: "sachkr0810.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753968/Sachin_Kumar_mppltl_yffpix.avif",
    linkedIn:
      "https://www.linkedin.com/in/sachin-kumar-32b781312?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    hall: "RK",
  },
  {
    index: 34,
    name: "Mr. Sanjay Ahari",
    dept: "CS",
    mail: "sanjayahari1704.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753962/Sanjay_Ahari_tcizvn_bmeieh.avif",
    linkedIn: "",
    hall: "MS",
  },
  {
    index: 35,
    name: "Mr. Satyam Kumar",
    dept: "IM",
    mail: "satyam.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753963/Satyam_Kumar_jwwblm_y6n0hz.avif",
    linkedIn: "",
    hall: "RK",
  },
  {
    index: 36,
    name: "Mr. Shivam Ahirwar",
    dept: "EE",
    mail: "ahirwarshivam7049@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753963/Shivam_Ahirwar_x9m9ox_o3y2d2.avif",
    linkedIn:
      "https://www.linkedin.com/in/shivam-ahirwar-425293311?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    hall: "Patel",
  },
  {
    index: 37,
    name: "Mr. Subhankar Majhi",
    dept: "MI",
    mail: "subhankar.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753964/Subhankar_Majhi_tmmtmy_wfntiw.avif",
    linkedIn: "",
    hall: "RK",
  },
  {
    index: 38,
    name: "Mr. Tanish Kumar",
    dept: "EC",
    mail: "Tanish.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753964/Tanish_Kumar_syafjs_ee3niw.avif",
    linkedIn: "",
    hall: "MMM",
  },
  {
    index: 39,
    name: "Mr. Undamati Joel Aakash",
    dept: "AE",
    mail: "ujaakash.24@kgpiian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753928/Joel_Aakash_Undamati_ekswpb_l0pd6y.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 40,
    name: "Mr. Uttam Meghwal",
    dept: "EE",
    mail: "Uttammeghwal.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753974/Uttam_Meghwal_kdgvqh_f90ijr.avif",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 41,
    name: "Mr. Vigyan Dev Gupta",
    dept: "MT",
    mail: "vigyandevgupta.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753974/Vigyandev_Gupta_ywhkor_jfdbzf.avif",
    linkedIn:
      "https://www.linkedin.com/in/vigyan-dev-gupta-0590aa206?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    hall: "RK",
  },
  {
    index: 42,
    name: "Mr. Vijay Meda",
    dept: "EC",
    mail: "captain.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753974/Vijay_Meda_sg5vxy_zxugmn.avif",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 43,
    name: "Mr. Yashraj Morode",
    dept: "CS",
    mail: "yashrajmorode.24@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747753975/Yashraj_Morode_rlfuch_bzpvrw.avif",
    linkedIn: "",
    hall: "MMM",
  },
];

export default FirstFamData;
