const FirstFamData = [
  {
    id: 0,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Abhinam Dutta",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 1,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Akhilesh Dixit",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Akshat Sharma",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Aman Rathore",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Amit Kumar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Anuruddh Kumar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Aryan Dhanger",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Avinash Sappati",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Ayan Mallick",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Ayush Kumar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Bibek Biswas",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Chetna Kanesh",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Deepesh",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Dhananjay Sarkar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Golu Kumar Sagar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Himanshu Malik",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Hiran Jyoti Deori",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Karthik Meesala",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Kiran Lakkam",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mayank Singh",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Monika Dhakad",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 21,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Muskan Verma",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 22,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Nayan Balpande",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 23,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Nisit",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 24,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Prabhat Prajapati",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 25,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Prabin Kumar Bhoi",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 26,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Prashik Mane",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 27,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Pratik Verma",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 28,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Preeti Chaudhary",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 29,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Priyanshu Gautam",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 30,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Priyanshu Gupta",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 31,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Rahul Borkar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 32,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Rajesh Kumar Bahera",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 33,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Rajmal Murmu",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 34,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Rishikesh Kumar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 35,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Sachin Kumar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 36,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Sanjay Ahari",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 37,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Satyam Kumar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 38,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Shivam Ahirwar",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 39,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Subhankar Majhi",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 40,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Tanish",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 41,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Undamati Joel Aakash",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 42,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Vigyandev Gupta",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 43,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Uttam",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 44,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Vijay Meda",
    dept: "ME",
    hall: "MMH",
  },
  {
    id: 45,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Yashraj Morode",
    dept: "ME",
    hall: "MMH",
  },
];

export default FirstFamData;
