const FirstFamData = [
  {
    id: 0,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Abhinam Dutta",
    dept: "ME",
    hall: "LBS",
    mail: "abc",
    linkedIn: "",
  },
  {
    id: 1,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Akhilesh Dixit",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Akshat Sharma",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Aman Rathore",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Amit Kumar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Anuruddh Kumar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Aryan Dhanger",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Avinash Sappati",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Ayan Mallick",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Ayush Kumar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Bibek Biswas",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Ms. Chetna Kanesh",
    dept: "ME",
    hall: "SNVH",
    mail: "",
    linkedIn: "",
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Deepesh",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Dhananjay Sarkar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Golu Kumar Sagar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Himanshu Malik",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Hiran Jyoti Deori",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Karthik Meesala",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Kiran Lakkam",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Mayank Singh",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Ms. Monika Dhakad",
    dept: "ME",
    hall: "SNVH",
    mail: "",
    linkedIn: "",
  },
  {
    id: 21,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Ms. Muskan Verma",
    dept: "ME",
    hall: "SNVH",
    mail: "",
    linkedIn: "",
  },
  {
    id: 22,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Nayan Balpande",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 23,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Nisit",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 24,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Prabhat Prajapati",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 25,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Prabin Kumar Bhoi",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 26,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Prashik Mane",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 27,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Pratik Verma",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 28,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Ms.Preeti Chaudhary",
    dept: "ME",
    hall: "SNVH",
    mail: "",
    linkedIn: "",
  },
  {
    id: 29,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Priyanshu Gautam",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 30,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Priyanshu Gupta",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 31,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Rahul Borkar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 32,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Rajesh Kumar Bahera",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 33,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Rajmal Murmu",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 34,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Rishikesh Kumar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 35,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Sachin Kumar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 36,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Sanjay Ahari",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 37,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Satyam Kumar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 38,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Shivam Ahirwar",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 39,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Subhankar Majhi",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 40,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Tanish",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 41,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Undamati Joel Aakash",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 42,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Vigyandev Gupta",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 43,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Uttam",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 44,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Vijay Meda",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
  {
    id: 45,
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg",
    name: "Mr. Yashraj Morode",
    dept: "ME",
    hall: "LBS",
    mail: "",
    linkedIn: "",
  },
];

export default FirstFamData;
