const SecondFamData = [
  {
    index: 0,
    name: "Mr. Abhay Mishra",
    dept: "EC",
    mail: "abhaymishra77275@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402094/Abhay_Mishra_lflklg.jpg",
    linkedIn: "",
    hall: "Azad",
  },
  {
    index: 1,
    name: "Mr. Abhinav Kumar Choudhary",
    dept: "AG",
    mail: "abhinavkumarchoudhary@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747401971/Abhinav_Kumar_Chaudhary_ahsqwx.jpg",
    linkedIn: "",
    hall: "",
  },
  {
    index: 2,
    name: "Ms. Akanksha Kushwaha",
    dept: "IE",
    mail: "akankshakushwaha0111@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402209/Akanksha_Kushwaha_gvn4ml.jpg",
    linkedIn: "",
    hall: "MT",
  },
  {
    index: 3,
    name: "Mr. Amit Dinkar",
    dept: "AE",
    mail: "amiitd0704@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402317/Amit_Dinkar_fz2z2z.jpg",
    linkedIn: "https://www.linkedin.com/in/amit-dinkar-454b73288",
    hall: "MSH",
  },
  {
    index: 4,
    name: "Mr. Animesh Mondal",
    dept: "EE",
    mail: "animeshtxt@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402391/Animesh_Mondal_ncvp4c.jpg",
    linkedIn: "https://www.linkedin.com/in/animesh-mondal-4b702527a/",
    hall: "",
  },
  {
    index: 5,
    name: "Mr. Anshuman Acharya",
    dept: "CH",
    mail: "anshuman2004@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402466/Anshuman_Acharya_rlaqrq.jpg",
    linkedIn: "",
    hall: "VS",
  },
  {
    index: 6,
    name: "Mr. Anushesh Jumale",
    dept: "EE",
    mail: "Anushesh@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402638/Anushesh_Jumale_wyjwp1.jpg",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 7,
    name: "Mr. Arnab Chakraborty",
    dept: "CH",
    mail: "I_am_arnab@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402537/Arnab_Chakraborty_so1pdv.jpg",
    linkedIn: "https://www.linkedin.com/in/arnab-chakraborty-264a43289",
    hall: "",
  },
  {
    index: 8,
    name: "Mr. Arvind Meena",
    dept: "BT",
    mail: "arvindmeena@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402781/Arvind_Meena_zsll0a.jpg",
    linkedIn: "https://www.linkedin.com/in/arvind-meena-78a258288",
    hall: "MMH",
  },
  {
    index: 9,
    name: "Mr. Ashutosh Ranjan",
    dept: "ME",
    mail: "ashutoshranjan@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747402893/Ashutosh_Ranjan_flro1b.jpg",
    linkedIn: "https://www.linkedin.com/in/ashutosh-ranjan-a33a4927a",
    hall: "RP",
  },
  {
    index: 10,
    name: "Mr. Ashwini Kumar",
    dept: "AG",
    mail: "ashwinikumar45@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403177/Ashwini_kumar_uggowl.jpg",
    linkedIn: "https://www.linkedin.com/in/wini045",
    hall: "RK",
  },
  {
    index: 11,
    name: "Mr. Bijaya Kumar Behera",
    dept: "BT",
    mail: "bijayabehera745@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403013/Bijay_Kumar_Behera_su8rmg.jpg",
    linkedIn: "",
    hall: "",
  },
  {
    index: 12,
    name: "Mr. Ganesh Vasuniya",
    dept: "AG",
    mail: "ganesh98@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403297/Ganesh_Vasuniya_lee4cu.jpg",
    linkedIn: "https://www.linkedin.com/in/ganesh-vasuniya-02aba32b2",
    hall: "JCB",
  },
  {
    index: 13,
    name: "Ms. Hawa Khatoon",
    dept: "CH",
    mail: "Hawakhatoon131@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403443/Hawa_Khatoon_hpx4pq.jpg",
    linkedIn: "https://in.linkedin.com/in/hawa-khatoon-362a7a2b6",
    hall: "MT",
  },
  {
    index: 14,
    name: "Ms. Jyoti Hembram",
    dept: "EE",
    mail: "jyotihembram.studyat@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403535/Jyoti_Hembram_jly0hq.jpg",
    linkedIn: "https://www.linkedin.com/in/jyoti-hembram-341512288",
    hall: "MT",
  },
  {
    index: 15,
    name: "Mr. Krishna Singha",
    dept: "CS",
    mail: "krishnasingha426@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403635/Krishna_Singha_kngavp.jpg",
    linkedIn: "https://www.linkedin.com/in/krishnasingha/",
    hall: "VSH",
  },
  {
    index: 16,
    name: "Mr. Mohit Kumar",
    dept: "EC",
    mail: "mk8750351763@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403787/Mohit_Kumar_zmv5np.jpg",
    linkedIn: "",
    hall: "LLR",
  },
  {
    index: 17,
    name: "Mr. Nishant Meena",
    dept: "EE",
    mail: "meenanishant36@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403872/Nishant_Meena_bi57k1.jpg",
    linkedIn: "",
    hall: "ABV",
  },
  {
    index: 18,
    name: "Mr. Om Dabhade",
    dept: "IE",
    mail: "dabhadeom187@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747403979/Om_Dabhade_z0sxjw.jpg",
    linkedIn: "",
    hall: "Azad",
  },
  {
    index: 19,
    name: "Mr. Om Shanti",
    dept: "CS",
    mail: "oms409793@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404185/Om_Shanti_gcsvtk.jpg",
    linkedIn: "http://linkedin.com/in/om-shanti-22885328o",
    hall: "Azad",
  },
  {
    index: 20,
    name: "Mr. Prabhat Kumar",
    dept: "MA",
    mail: "prabhatjha01@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404288/Prabhat_Jha_bot6r5.jpg",
    linkedIn: "https://www.linkedin.com/in/prabhat-kumar-134228255",
    hall: "ABV",
  },
  {
    index: 21,
    name: "Mr. Praveen Oraon",
    dept: "ME",
    mail: "praveenoraon518@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404374/Praveen_Oraon_zqeuwe.jpg",
    linkedIn: "",
    hall: "",
  },
  {
    index: 22,
    name: "Mr. Raja Mandal",
    dept: "CS",
    mail: "rajamandal5346@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404490/Raja_Mandal_nmtbza.jpg",
    linkedIn: "",
    hall: "",
  },
  {
    index: 23,
    name: "Mr. Ramesh Kumar Das",
    dept: "EE",
    mail: "kramesh1845@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404610/Ramesh_Kumar_mpfxxp.jpg",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 24,
    name: "Ms. Sangeeta Kumari Mandal",
    dept: "CS",
    mail: "sangeeta180703@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404750/Sangeeta_Kumari_Mandal_a35dfb.jpg",
    linkedIn: "",
    hall: "MT",
  },
  {
    index: 25,
    name: "Mr. Shreyash Dhakate",
    dept: "IM",
    mail: "shreyashdhakate@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747404865/Shreyash_Dhakate_nwu1vx.jpg",
    linkedIn: "",
    hall: "MMH",
  },
  {
    index: 26,
    name: "Mr. Subhajit Mondal",
    dept: "IM",
    mail: "subhajit2005@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747405997/Subhajit_Mondal_odmvbq.jpg",
    linkedIn: "",
    hall: "RP",
  },
  {
    index: 27,
    name: "Mr. Subhajit Sarkar",
    dept: "EC",
    mail: "subhajit35sarkar@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747406161/Subhajit_Sarkar_sjusnh.jpg",
    linkedIn: "",
    hall: "MMH",
  },
  {
    index: 28,
    name: "Mr. Sukumar Singh",
    dept: "CS",
    mail: "sukumarsingh@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747406279/Sukumar_qjkqpc.jpg",
    linkedIn: "",
    hall: "MSH",
  },
  {
    index: 29,
    name: "Mr. Sunny",
    dept: "IE",
    mail: "sunnyscnt458@gmail.com",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747406449/Sunny_lzoth5.jpg",
    linkedIn: "https://www.linkedin.com/in/sunny-065a19288",
    hall: "Nehru",
  },
  {
    index: 30,
    name: "Mr. Suvadip Bhuiya",
    dept: "CS",
    mail: "suvadipbhuiya09@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747406723/Suvadip_Bhaiya_xhzvsy.jpg",
    linkedIn: "",
    hall: "Nehru",
  },
  {
    index: 31,
    name: "Mr. Swarup Jayaram Dhanavade",
    dept: "MI",
    mail: "swarupd@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747406803/Swarup_Dhanavade_fodfed.jpg",
    linkedIn: "https://www.linkedin.com/in/swarup-dhanavade",
    hall: "Nehru",
  },
  {
    index: 32,
    name: "Mr. Vikash Rathore",
    dept: "CH",
    mail: "vikashrathore@kgpian.iitkgp.ac.in",
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747406937/Vikash_Rathore_pint2b.jpg",
    linkedIn: "",
    hall: "Patel",
  },
];

export default SecondFamData;
