const SecondFamData = [
  { id: 0, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Abhay Mishra", dept: "ME", hall: "MMH" },
  { id: 1, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Abhinav Kumar Choudhary", dept: "ME", hall: "MMH" },
  { id: 2, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Miss Akanksha Kushwaha", dept: "ME", hall: "MMH" },
  { id: 3, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Amit Dinkar", dept: "ME", hall: "MMH" },
  { id: 4, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Animesh Mondal", dept: "ME", hall: "MMH" },
  { id: 5, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Anshuman Acharya", dept: "ME", hall: "MMH" },
  { id: 6, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Anushesh Jumale", dept: "ME", hall: "MMH" },
  { id: 7, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Arnab Chakraborty", dept: "ME", hall: "MMH" },
  { id: 8, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Arvind Meena", dept: "ME", hall: "MMH" },
  { id: 9, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Ashutosh Ranjan", dept: "ME", hall: "MMH" },
  { id: 10, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Ashwini Kumar", dept: "ME", hall: "MMH" },
  { id: 11, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Bijay", dept: "ME", hall: "MMH" },
  { id: 12, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Ganesh Vasuniya", dept: "ME", hall: "MMH" },
  { id: 13, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Miss Hawa Khatoon", dept: "ME", hall: "MMH" },
  { id: 14, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Miss Jyoti Hembram", dept: "ME", hall: "MMH" },
  { id: 15, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Krishna Singha", dept: "ME", hall: "MMH" },
  { id: 16, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Mohit Kumar", dept: "ME", hall: "MMH" },
  { id: 17, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Nishant Meena", dept: "ME", hall: "MMH" },
  { id: 18, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Om Dabhade", dept: "ME", hall: "MMH" },
  { id: 19, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Om Shanti", dept: "ME", hall: "MMH" },
  { id: 20, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Prabhat Kumar", dept: "ME", hall: "MMH" },
  { id: 21, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Praveen Kumar", dept: "ME", hall: "MMH" },
  { id: 22, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Prithviraj Nunisa", dept: "ME", hall: "MMH" },
  { id: 23, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Raja Mandal", dept: "ME", hall: "MMH" },
  { id: 24, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Ramesh Kumar Das", dept: "ME", hall: "MMH" },
  { id: 25, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Miss Sangeeta Mondal", dept: "ME", hall: "MMH" },
  { id: 26, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Shani Maurya", dept: "ME", hall: "MMH" },
  { id: 27, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Shreyash Dhakate", dept: "ME", hall: "MMH" },
  { id: 28, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Subhajit Sarkar", dept: "ME", hall: "MMH" },
  { id: 29, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Subhojit Mondal", dept: "ME", hall: "MMH" },
  { id: 30, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Sukumar Singh", dept: "ME", hall: "MMH" },
  { id: 31, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Sunny Kumar", dept: "ME", hall: "MMH" },
  { id: 32, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Suvadip Bhuiya", dept: "ME", hall: "MMH" },
  { id: 33, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Swarup Dhanawade", dept: "ME", hall: "MMH" },
  { id: 34, img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1746180942/images_1_eqjrit.jpg", name: "Mr. Vikash Rathore", dept: "ME", hall: "MMH" }
];

export default SecondFamData;