export const CouncilData = [
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748012053/Ashutosh_wvgdts.avif",
    title: "Mr. Ashutosh ",
    portfolio: "Vice President, Events - DST & Freshmen",
    mobile: "+91 9058887078",
    mail: "ashutosh.daan@gmail.com",
    year: "5th",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723339/Paramjeet_Saini_xolxxj.avif",
    title: "Mr. Paramjeet Saini",
    portfolio: "Senior Sectretary, DST(JNV)",
    mail: "paramjeetsaini@kgpian.iitkgp.ac.in",
    mobile: "+91 6397189676",
    year: "4th",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1748023103/Shani_Maurya_cpux6d.avif",
    title: "Mr. Shani Maurya",
    portfolio: "College Representative, IIT Kharagpur",
    mail: "shauryashanisaini@gmail.com",
    mobile: "+91 9555439091",
    year: "3rd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723437/Mohit_Kumar_h57d5w.avif",
    title: "Mr. Mohit Kumar",
    portfolio: "Junior Secretary, DST(Non-JNV)",
    mail: "mk8750351763@kgpian.iitkgp.ac.in",
    mobile: "+91 8384078167",
    year: "3rd",
  },
  {
    img: "https://res.cloudinary.com/dcwwptwzt/image/upload/v1747723597/Swarup_Dhanavade_ncjz8k.avif",
    title: "Mr. Swarup Dhanavade",
    portfolio: "Junior Secretary, DST(JNV)",
    mail: "swarupd@kgpian.iitkgp.ac.in",
    mobile: "+91 9423751729",
    year: "3rd",
  },
];
